import React from 'react';
import { useParams, Link } from 'react-router-dom';
import { useAppContext } from '../context/AppContext';

/*
  displays order confirmation after successful checkout.
  shows a unique order ID and total for visual feedback.
*/

const OrderConfirmationPage = () => {
    // get the order ID from the URL parameters (defined in route: /order-confirmation/:id)
    const { id } = useParams();

    // retrieve all orders from global context to access stored order data
    const { orders } = useAppContext();
    
    // find the specific order matching the ID from the URL
    const order = orders.find(o => o.id === id);

    if (!order) {
        return (
            <div className="confirmation-page">
                <h1>Order not found.</h1>
                <Link to="/">Return to home page</Link>
            </div>
        );
    }

    return (
        <div className="confirmation-page">
            <h1>Thank you for your order!</h1>
            
            {/* display the unique order ID generated by placeOrder in AppContext */}
            <p>Order ID: <strong>{order.id}</strong></p>
            
            <p>Total: <strong>${order.total.toFixed(2)}</strong></p>
            
            <Link to="/account" className="to-order-page">
                Go to User's Account
            </Link>
        </div>
    );
};

export default OrderConfirmationPage;
